# Generated by Django 5.1.7 on 2025-04-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prix',
            new_name='prix_achat',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
