# Generated by Django 5.1.7 on 2025-04-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0002_alter_lignevente_prix_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignevente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=1000, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
