# Generated by Django 5.1.7 on 2025-04-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant_total',
        ),
    ]
